GET https://localhost:5081/secret/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFsZXgiLCJzdWIiOiJhbGV4IiwianRpIjoiNTE5YmFiYTEiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDoxNzg2MiIsImh0dHBzOi8vbG9jYWxob3N0OjQ0MzI0IiwiaHR0cDovL2xvY2FsaG9zdDo1MDEyIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NTA4MSJdLCJuYmYiOjE3MTc2OTc2ODMsImV4cCI6MTcyNTY0NjQ4MywiaWF0IjoxNzE3Njk3NjgzLCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.FKwDw-vALcdaU_Ac9-hzbQdUKVi_6J6PScOh3DyjifE